# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vaibhav Gupta
title: Data Scientist
email: vaibhav.gupta@vanderbilt.edu
website: www.guptavaibhav35.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username: sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# google_scholar:

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Vaibhav Gupta, and I am a data scientist who thrives on turning data into impactful solutions. Driven by boundless curiosity and a love for innovation, I immerse myself in the intricate worlds of AI, data science, machine learning, data analysis, and cutting-edge technologies like Generative AI and large language models (LLMs). My academic journey at Vanderbilt University has allowed me to dive deep into these fields, where I’m not just exploring the trends—I’m helping to shape them. 
  My experience spans a variety of domains, from finance to education to healthcare. I’ve crafted AI models that optimize financial strategies, developed advanced audio analysis tools that enhance classroom learning, engineered systems for medical image analysis, and performed data analysis that uncovers actionable insights. My work with Generative AI and LLMs, including building sophisticated models that generate human-like text and improve decision-making processes, is a key part of how I approach challenges. Whether it's constructing robust data pipelines, fine-tuning models with Python, PyTorch, and TensorFlow, or deploying solutions on cloud platforms like AWS, GCP, and Azure, I approach each project with a joyful blend of creativity and precision.
  Every line of code I write, every dataset I analyze, and every model I fine-tune is a step toward expanding the frontiers of technology. This work isn’t just my career—it’s my joyful contribution to a smarter, more connected world. Explore my portfolio to see how I merge cutting-edge technology with thoughtful execution, transforming complex challenges across diverse domains into elegant, impactful solutions.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vanderbilt University
        caption: 2023 - 2025
        sub_title: Masters of Science in Computer Science
        description: | # this will include new lines to allow paragraphs
          **Coursework:** Natural language processing, Deep learning, Social network analysis, Foundations of ML, Advanced AI, Reinforcement learning, Cloud Computing and Open Source Programming in Medical Image Analysis.

      - layout: left
        title: Graphic Era Deemed to be University
        caption: 2015 - 2019
        sub_title: Bachelor's of Technology in Computer Science
        description: | # this will include new lines to allow paragraphs
          **Coursework:**

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Science Intern
        link: https://peabody.vanderbilt.edu/academics/departments/special-education/
        link_text: Lab Website
        sub_title: SPED Lab, Vanderbilt Peobody College
        caption: May 2024 - Present
        quote: >
          Revolutionizing classroom analysis by building advanced audio diarization tools using Deep Denoising Autoencoders and wav2vec2, alongside cutting-edge pipelines like Whisper and LangChain, achieving game-changing 92% segmentation and 98% transcription accuracy to redefine teaching insights.
        description: | # this will include new lines to allow paragraphs
          - Developed an advanced audio diarization application using Deep Denoising Autoencoders and huggingface wav2vec2 transformers to tokenize and embed classroom audio, segmenting student and teacher voices from the classroom audio with a 92% accuracy.

          - Deployed a pipeline using LangChain to transcribe segmented teacher audio using Whisper with 98% accuracy, and used DistilBERT to categorize teaching instructions, offering insights into teaching methods and their impact on student learning.

      - layout: left
        title: Generative AI Engineer Intern
        link: https://www.vanderbilt.edu/generative-ai/
        link_text: Lab and Product Website
        sub_title: Vanderbilt's Generative AI Initiative
        caption: May 2024 - August 2024
        quote: >
          Transforming RAG performance by engineering an advanced pipeline with LangChain and Claude-3-Sonnet, achieving a BERTScore of 0.93, while leveraging transfer learning to fine-tune Llama 3.0 on financial data, building a Streamlit AI assistant that boosted fund performance by $50K in one quarter with actionable insights powered by Sentence-BERT.
        description: | # this will include new lines to allow paragraphs
          - Engineered an advanced RAG pipeline with LangChain, inferring Claude-3-Sonnet LLM to generate 5 key questions and answers from documents, and synthesizing responses with user prompt to produce comprehensive final response using ChatGPT-4o.

          - Implemented comprehensive RAG pipeline testing, evaluating using BLEU, ROUGE, PERPLEXITY, BERTScore, Diversity, and Fluency metrics, achieving an exceptional BERTScore of 0.93.

          - Employed transfer learning to fine-tune Llama 3.0 on extensive financial data using PyTorch, and developed a Streamlit AI assistant to evaluate fund managers' performance and recommend investment strategies, resulting in a $50,000 profit increase in one quarter.

          - Developed an actionable insight generator using Bidirectional Auto-Regressive Transformers and Sentence-BERT, to streamline daily market news and meeting transcripts into three key actionable recommendations for fund managers to perform as a daily task.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-livereload
